### PR TITLE
Bump kube-burner version

### PR DESCRIPTION
**Pull request by rsevilla87**
## Type of change

- [ ] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Bumping kube-burner version

## Related Tickets & Documents

- Related Issue #
- Closes #

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

### CODE REVIEW

**Review by afcollins — APPROVED** [review]
LGTM

**Comment by rsevilla87** [comment]
> LGTM

This version not relevant from a CPT side, but it ships some features I need for Service Mesh testing

**Review by vishnuchalla — APPROVED** [review]
lgtm

**Comment by vishnuchalla** [comment]
> > LGTM
> 
> This version not relevant from a CPT side, but it ships some features I need for Service Mesh testing

Anyhow merging these changes shouldn't effect our CPT runs I believe, as we have version locking enabled over there.

**Comment by rsevilla87** [comment]
> > > LGTM
> > 
> > 
> > This version not relevant from a CPT side, but it ships some features I need for Service Mesh testing
> 
> Anyhow merging these changes shouldn't effect our CPT runs I believe, as we have version locking enabled over there.

correct, I was just adding some context on why we shouldn't consider using this version in CPT

**Pull request merged**
