### PR TITLE
Enable health check by default

### PR DESCRIPTION
**Pull request by rsevilla87**
## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [x] Optimization
- [ ] Documentation Update

## Description

Enabling health check by default

## Related Tickets & Documents

- Related Issue #79
- Closes #

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

### CODE REVIEW

**Comment by paigerube14** [comment]
I feel like this could impact a lot of tests, if we add this in here, will we be able to test in e2e-benchmarking/prow before fully merging that we can feel more confident in tests consistently passing before going fully in with it?

**Comment by rsevilla87** [comment]
> I feel like this could impact a lot of tests, if we add this in here, will we be able to test in e2e-benchmarking/prow before fully merging that we can feel more confident in tests consistently passing before going fully in with it?

yeah, the process of adding new features is quite safe and requires several steps:

- Merge commit
- Cut new release of kube-burner-ocp
- Update kube-burner-ocp version in e2e-benchmarking
- Run CI tests 
- Merge PR in e2e-benchmarking
- Cut new release in e2e-benchmarking

**Comment by rsevilla87** [comment]
cc @kube-burner/ocp-perfscale @kube-burner/ocp-perfscale-telco , take a look please, this update is important

**Review by krishvoor — APPROVED** [review]
/lgtm

**Comment by vishnuchalla** [comment]
> > I feel like this could impact a lot of tests, if we add this in here, will we be able to test in e2e-benchmarking/prow before fully merging that we can feel more confident in tests consistently passing before going fully in with it?
> 
> yeah, the process of adding new features is quite safe and requires several steps:
> 
> * Merge commit
> * Cut new release of kube-burner-ocp
> * Update kube-burner-ocp version in e2e-benchmarking
> * Run CI tests
> * Merge PR in e2e-benchmarking
> * Cut new release in e2e-benchmarking

@rsevilla87 for this change, we might also want to run some rehearsals agaisnt a couple of periodic jobs in prow. Maybe against a baremetal and a non-baremetal ones.

**Comment by rsevilla87** [comment]
> > > I feel like this could impact a lot of tests, if we add this in here, will we be able to test in e2e-benchmarking/prow before fully merging that we can feel more confident in tests consistently passing before going fully in with it?
> > 
> > 
> > yeah, the process of adding new features is quite safe and requires several steps:
> > 
> > * Merge commit
> > * Cut new release of kube-burner-ocp
> > * Update kube-burner-ocp version in e2e-benchmarking
> > * Run CI tests
> > * Merge PR in e2e-benchmarking
> > * Cut new release in e2e-benchmarking
> 
> @rsevilla87 for this change, we might also want to run some rehearsals agaisnt a couple of periodic jobs in prow. Maybe against a baremetal and a non-baremetal ones.

correct, as many checks we can do before running it periodically the better

**Review by vishnuchalla — APPROVED** [review]
lgtm

**Review by paigerube14 — APPROVED** [review]
Lgtm

**Comment by rsevilla87** [comment]
@afcollins @jtaleric @dry923

**Comment by afcollins** [comment]
LGTM
+1 on the procedure in above [comment](https://github.com/kube-burner/kube-burner-ocp/pull/83#issuecomment-2208367103) so we understand any impacts

**Review by afcollins — APPROVED** [review]

**Pull request merged**
