### PR TITLE
[PERFSCALE-3594] Refactor udn-density-pods

### PR DESCRIPTION
**Pull request by krishvoor**
## Type of change

- [x] Refactor
- [ ] New feature
- [ ] Bug fix
- [x] Optimization
- [ ] Documentation Update

## Description

This PR refactors udn_l2 & udn_l3 code.
Adds conditional check to choose between udn_l2.yml/udn_l3.yml

## Related Tickets & Documents

- Related Issue #
- Closes #

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

### CODE REVIEW

**Review by venkataanil — COMMENTED** [review]
Can we have only one commit? (at least commit 2 is not needed).

**Comment by rsevilla87** [comment]
> Can we have only one commit? (at least commit 2 is not needed).

no worries, we squash the commits into a single one, also, having multiple commits in a single PR is a good practice to track new changes and help reviewers.

**Comment by mohit-sheth** [comment]
can we log a statement which informs that it is using L2/L3
also we need to add that metadata to our kube-burner dash so that we know what report we are looking at

**Comment by krishvoor** [comment]
> can we log a statement which informs that it is using L2/L3 also we need to add that metadata to our kube-burner dash so that we know what report we are looking at

Done, ptal

**Review by venkataanil — APPROVED** [review]
LGTM

**Pull request merged**
