### PR TITLE
Remove metadata from all documents except jobSummary

### PR DESCRIPTION
**Pull request by rsevilla87**
## Type of change

- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [x] Optimization
- [ ] Documentation Update

## Description

Follow-up of https://github.com/kube-burner/kube-burner/pull/665
Removing cluster metadata from all documents except `jobSummary`

A example of the size reduction after running `kube-burner-ocp cluster-density-v2 --iterations=20 --local-indexing --churn-cycles=5` in a 3 node cluster:

```console
$ du -hs collected-metrics-a0d6ee15-a1ea-42d1-9479-7e2aef42838a collected-metrics-e9552b2e-78a9-4c9d-8771-6b67077cc6d1                                                                      
13M     collected-metrics-a0d6ee15-a1ea-42d1-9479-7e2aef42838a <--After                                                       
23M     collected-metrics-e9552b2e-78a9-4c9d-8771-6b67077cc6d1 <- Before
```

For the time being, using my own fork as `kube-burner` dependency, changes are available at https://github.com/kube-burner/kube-burner/compare/main...rsevilla87:kube-burner:remove-metadata

Next steps:

- Verify nothing breaks in
  - [x] CPT dashboard
  - [x] Grafana dashboards
  - [x] Orion
- Open definitive PR in the core `kube-burner` repo
- Cut new kube-burner release
- Merge this PR
- Cut new `kube-burner-ocp` release

### CODE REVIEW

**Comment by rsevilla87** [comment]
Had to do some modifications to the kube-burner report mode dashboard to work well -> https://grafana.rdu2.scalelab.redhat.com:3000/d/edrtolnf1h1q8d/kube-burner-report-mode-no-metadata?orgId=1

**Comment by afcollins** [comment]
Could you host the collected-metrics archive somewhere we can look at?

**Review by afcollins — COMMENTED** [review]
LGTM . Should this PR be a draft until the other checkboxes are checked?

**Comment by vishnuchalla** [comment]
cc: @shashank-boyapally @jtaleric This is the PR to address your metadata concerns [regarding orion](https://redhat-internal.slack.com/archives/C05CDC19ZKJ/p1721676228429499) w.r.t kube-burner.

**Review by jtaleric — APPROVED** [review]
lgtm

**Pull request merged**
